# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messages_struct_pb2 as messages__struct__pb2


class ServicesStub(object):
  """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/messages_struct.proto

  A definição dos serviços
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTwoIntValues = channel.unary_unary(
        '/messages_struct.Services/AddTwoIntValues',
        request_serializer=messages__struct__pb2.AddRequest.SerializeToString,
        response_deserializer=messages__struct__pb2.AddResult.FromString,
        )
    self.NoArgument_NoReturn = channel.unary_unary(
        '/messages_struct.Services/NoArgument_NoReturn',
        request_serializer=messages__struct__pb2.Empty.SerializeToString,
        response_deserializer=messages__struct__pb2.Empty.FromString,
        )
    self.OneLongArgument_OneLongReturn = channel.unary_unary(
        '/messages_struct.Services/OneLongArgument_OneLongReturn',
        request_serializer=messages__struct__pb2.Long.SerializeToString,
        response_deserializer=messages__struct__pb2.Long.FromString,
        )
    self.GetMiddleArrayValue = channel.unary_unary(
        '/messages_struct.Services/GetMiddleArrayValue',
        request_serializer=messages__struct__pb2.ItemQuery.SerializeToString,
        response_deserializer=messages__struct__pb2.ItemResponse.FromString,
        )
    self.GetCountry_PersonPhone = channel.unary_unary(
        '/messages_struct.Services/GetCountry_PersonPhone',
        request_serializer=messages__struct__pb2.Person.SerializeToString,
        response_deserializer=messages__struct__pb2.Country.FromString,
        )
    self.EightLongsArguments_OneLongReturn = channel.unary_unary(
        '/messages_struct.Services/EightLongsArguments_OneLongReturn',
        request_serializer=messages__struct__pb2.RealLong.SerializeToString,
        response_deserializer=messages__struct__pb2.Long.FromString,
        )
    self.OneStringArgument_ReverseStringReturn = channel.unary_unary(
        '/messages_struct.Services/OneStringArgument_ReverseStringReturn',
        request_serializer=messages__struct__pb2.String.SerializeToString,
        response_deserializer=messages__struct__pb2.String.FromString,
        )
    self.OneStringArgument_ArrayReturn = channel.unary_unary(
        '/messages_struct.Services/OneStringArgument_ArrayReturn',
        request_serializer=messages__struct__pb2.String.SerializeToString,
        response_deserializer=messages__struct__pb2.StringArray.FromString,
        )
    self.ThreeDoubleArgument_DoubleReturn = channel.unary_unary(
        '/messages_struct.Services/ThreeDoubleArgument_DoubleReturn',
        request_serializer=messages__struct__pb2.RealDouble.SerializeToString,
        response_deserializer=messages__struct__pb2.Double.FromString,
        )
    self.AddTwoIntValues_SignedInt = channel.unary_unary(
        '/messages_struct.Services/AddTwoIntValues_SignedInt',
        request_serializer=messages__struct__pb2.AddRequest_Signed.SerializeToString,
        response_deserializer=messages__struct__pb2.AddResponse_Signed.FromString,
        )
    self.AddTwoIntValues_FixedInt = channel.unary_unary(
        '/messages_struct.Services/AddTwoIntValues_FixedInt',
        request_serializer=messages__struct__pb2.AddRequest_Fixed.SerializeToString,
        response_deserializer=messages__struct__pb2.AddResponse_Fixed.FromString,
        )
    self.BinarySearch = channel.unary_unary(
        '/messages_struct.Services/BinarySearch',
        request_serializer=messages__struct__pb2.Tuple.SerializeToString,
        response_deserializer=messages__struct__pb2.Boolean.FromString,
        )
    self.OneLongArgument_OneOf_OneLongReturn = channel.unary_unary(
        '/messages_struct.Services/OneLongArgument_OneOf_OneLongReturn',
        request_serializer=messages__struct__pb2.OneofLong.SerializeToString,
        response_deserializer=messages__struct__pb2.Long.FromString,
        )
    self.SetHashFunction = channel.unary_unary(
        '/messages_struct.Services/SetHashFunction',
        request_serializer=messages__struct__pb2.HashFunction.SerializeToString,
        response_deserializer=messages__struct__pb2.Hash.FromString,
        )


class ServicesServicer(object):
  """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/messages_struct.proto

  A definição dos serviços
  """

  def AddTwoIntValues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NoArgument_NoReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OneLongArgument_OneLongReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMiddleArrayValue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCountry_PersonPhone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EightLongsArguments_OneLongReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OneStringArgument_ReverseStringReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OneStringArgument_ArrayReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ThreeDoubleArgument_DoubleReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTwoIntValues_SignedInt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTwoIntValues_FixedInt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BinarySearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OneLongArgument_OneOf_OneLongReturn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetHashFunction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTwoIntValues': grpc.unary_unary_rpc_method_handler(
          servicer.AddTwoIntValues,
          request_deserializer=messages__struct__pb2.AddRequest.FromString,
          response_serializer=messages__struct__pb2.AddResult.SerializeToString,
      ),
      'NoArgument_NoReturn': grpc.unary_unary_rpc_method_handler(
          servicer.NoArgument_NoReturn,
          request_deserializer=messages__struct__pb2.Empty.FromString,
          response_serializer=messages__struct__pb2.Empty.SerializeToString,
      ),
      'OneLongArgument_OneLongReturn': grpc.unary_unary_rpc_method_handler(
          servicer.OneLongArgument_OneLongReturn,
          request_deserializer=messages__struct__pb2.Long.FromString,
          response_serializer=messages__struct__pb2.Long.SerializeToString,
      ),
      'GetMiddleArrayValue': grpc.unary_unary_rpc_method_handler(
          servicer.GetMiddleArrayValue,
          request_deserializer=messages__struct__pb2.ItemQuery.FromString,
          response_serializer=messages__struct__pb2.ItemResponse.SerializeToString,
      ),
      'GetCountry_PersonPhone': grpc.unary_unary_rpc_method_handler(
          servicer.GetCountry_PersonPhone,
          request_deserializer=messages__struct__pb2.Person.FromString,
          response_serializer=messages__struct__pb2.Country.SerializeToString,
      ),
      'EightLongsArguments_OneLongReturn': grpc.unary_unary_rpc_method_handler(
          servicer.EightLongsArguments_OneLongReturn,
          request_deserializer=messages__struct__pb2.RealLong.FromString,
          response_serializer=messages__struct__pb2.Long.SerializeToString,
      ),
      'OneStringArgument_ReverseStringReturn': grpc.unary_unary_rpc_method_handler(
          servicer.OneStringArgument_ReverseStringReturn,
          request_deserializer=messages__struct__pb2.String.FromString,
          response_serializer=messages__struct__pb2.String.SerializeToString,
      ),
      'OneStringArgument_ArrayReturn': grpc.unary_unary_rpc_method_handler(
          servicer.OneStringArgument_ArrayReturn,
          request_deserializer=messages__struct__pb2.String.FromString,
          response_serializer=messages__struct__pb2.StringArray.SerializeToString,
      ),
      'ThreeDoubleArgument_DoubleReturn': grpc.unary_unary_rpc_method_handler(
          servicer.ThreeDoubleArgument_DoubleReturn,
          request_deserializer=messages__struct__pb2.RealDouble.FromString,
          response_serializer=messages__struct__pb2.Double.SerializeToString,
      ),
      'AddTwoIntValues_SignedInt': grpc.unary_unary_rpc_method_handler(
          servicer.AddTwoIntValues_SignedInt,
          request_deserializer=messages__struct__pb2.AddRequest_Signed.FromString,
          response_serializer=messages__struct__pb2.AddResponse_Signed.SerializeToString,
      ),
      'AddTwoIntValues_FixedInt': grpc.unary_unary_rpc_method_handler(
          servicer.AddTwoIntValues_FixedInt,
          request_deserializer=messages__struct__pb2.AddRequest_Fixed.FromString,
          response_serializer=messages__struct__pb2.AddResponse_Fixed.SerializeToString,
      ),
      'BinarySearch': grpc.unary_unary_rpc_method_handler(
          servicer.BinarySearch,
          request_deserializer=messages__struct__pb2.Tuple.FromString,
          response_serializer=messages__struct__pb2.Boolean.SerializeToString,
      ),
      'OneLongArgument_OneOf_OneLongReturn': grpc.unary_unary_rpc_method_handler(
          servicer.OneLongArgument_OneOf_OneLongReturn,
          request_deserializer=messages__struct__pb2.OneofLong.FromString,
          response_serializer=messages__struct__pb2.Long.SerializeToString,
      ),
      'SetHashFunction': grpc.unary_unary_rpc_method_handler(
          servicer.SetHashFunction,
          request_deserializer=messages__struct__pb2.HashFunction.FromString,
          response_serializer=messages__struct__pb2.Hash.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'messages_struct.Services', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
